project:
  type: website
  output-dir: docs

website:
  title: "Artur Baranov"
  favicon: images/fav.png
  google-analytics: "G-E5CQ2V5CKY"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: CV_abaranov.pdf
        text: CV
    right: 
      - icon: at
        href: mailto:artur.baranov@u.northwestern.edu
  page-footer:
    right: 'Created with [{{< fa brands github  >}}](https://github.com){target="_blank"}, [{{< fa brands r-project  >}}](https://posit.co){target="_blank"} and [Quarto](https://quarto.org/)'


format:
  html:
    theme:
      light: flatly
      dark: darkly
    mainfont: roboto
    css: styles.css
    toc: true
    




