project:
  type: website
  output-dir: docs

website:
  title: "{{< fa user-graduate >}} <b>Artur Baranov</b>"
  favicon: images/fav.png
  google-analytics: "G-E5CQ2V5CKY"
  navbar:
    pinned: true
    search: false
    left:
      - href: index.qmd
        text: "{{< fa home  >}} About"
      - href: projects.qmd
        text: "{{< fa book  >}} Projects"
      - href: CV_abaranov.pdf
        text: "{{< fa file >}} CV"
      - href: contacts.qmd
        text: "{{< fa address-book >}} Contacts"
    right:
      - icon: at
        href: mailto:artur.baranov@u.northwestern.edu
  page-footer:
    border: true
    right: 'Created with [{{< fa brands github  >}}](https://github.com){target="_blank"}, [{{< fa brands r-project  >}}](https://posit.co){target="_blank"} and [Quarto](https://quarto.org/){target="_blank"}'


format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    mainfont: roboto
    css: styles.css
    toc: true
    




